services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:example@db:3306/agenda
    volumes:
      - .:/var/www
    networks:
      - app-network
    ports:
      - "8000:8000"

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: agenda
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

volumes:
  db_data:
    
networks:
  app-network:
    driver: bridge